# Allow productpage to access reviews and details services
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: allow-productpage-out
  namespace: dev1
spec:
  tier: default
  order: 200
  selector: app == "productpage"
  egress:
  # Allow Pod-to-Pod direct access
  - action: Allow
    protocol: TCP
    destination:
      selector: app == "reviews" 
      namespaceSelector: name == "dev1"
      ports: [9080]  
  
  - action: Allow
    protocol: TCP
    destination:
      selector: app == "details"
      namespaceSelector: name == "dev1"
      ports: [9080]
      
  # Allow Service-based access
  - action: Allow
    protocol: TCP
    destination:
      services:
        name: reviews
        namespace: dev1
        
  - action: Allow
    protocol: TCP
    destination:
      services:
        name: details
        namespace: dev1