# Allow ingress traffic from productpage service to reviews service
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: allow-reviews-in
  namespace: dev1
spec:
  tier: default
  order: 300
  selector: app == "reviews"
  ingress:
  - action: Allow
    protocol: TCP
    source:
      services:
        name: productpage
        namespace: dev1
    destination:
      ports: [9080]
      
  # Allow direct pod-to-pod access
  - action: Allow
    protocol: TCP
    source:
      selector: app == "productpage"
      namespaceSelector: name == "dev1"
    destination:
      ports: [9080]
