- hosts: all
  become: yes
  tasks:
    - name: Allow user to run sudo without password
      lineinfile:
        path: /etc/sudoers
        line: "{{ ansible_user }} ALL=(ALL) NOPASSWD:ALL"
        validate: "visudo -cf %s"
        